GET http://localhost:10000/api/heartbeat

### Successful test: check response status is 200
GET  http://localhost:10000/api/heartbeat

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}